name: Run Python script when table_names.yml is modified

on:
  push:
    branches:
      - main
    paths:
      - 'table_names.yml'

env:
  AWS_REGION: eu-west-1
  AWS_ROLE_ARN: arn:aws:iam::124523898468:role/DMS-GITHUB-TEST
  REPLICATION_INSTANCE_ARN: ${{ vars.REPLICATION_INSTANCE_ARN }}
  SOURCE_ENDPOINT_ARN: ${{ vars.SOURCE_ENDPOINT_ARN }}
  TARGET_ENDPOINT_ARN: ${{ vars.TARGET_ENDPOINT_ARN }}

jobs:
  run-python-script:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: ${{ env.AWS_ROLE_ARN }}

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9  

      - name: Install PyYAML
        run: pip install pyyaml

      - name: Run Python script
        run: python dms-test.py  